apiVersion: apps/v1
kind: Deployment
metadata:
  name: aution-svc
spec:
  selector:
    matchLabels:
      app: aution-svc
  template:
    metadata:
      labels:
        app: aution-svc
    spec:
      containers:
      - name: aution-svc
        image: pdlearning/aution-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: auction-svc-config
        ports:
        - containerPort: 80
          name: web
        - containerPort: 7777
          name: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: aution-clusterip
spec:
  type: ClusterIP
  selector:
    app: aution-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc


