apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    app.kubernetes.io/name: ingress-svc
spec:
  ingressClassName: nginx
  tls:
  - hosts: # Created certificated using mkcert cmd -> mkcert -key-file server.key -cert-file server.crt app.carwars.local api.carwars.local id.carwars.local
    - app.carwars.local
    - api.carwars.local
    - id.carwars.local
    secretName: carwars-app-tls # K8S secret created using this cmd -> kubectl create secret tls carwars-app-tls --key server.key --cert server.crt
  rules:
  - host: app.carwars.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp-clusterip
            port: 
              number: 3000
  - host: api.carwars.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gateway-clusterip
            port: 
              number: 80
  - host: id.carwars.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: identity-clusterip
            port: 
              number: 80

